"""Add_daily_reports_table

Revision ID: 4fc9c8e54619
Revises: 
Create Date: 2025-11-19 11:54:44.561201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fc9c8e54619'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.UUID(), nullable=False, comment='보고서 ID'),
    sa.Column('owner', sa.String(length=100), nullable=False, comment='작성자'),
    sa.Column('date', sa.Date(), nullable=False, comment='보고서 날짜 (YYYY-MM-DD)'),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='CanonicalReport JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner', 'date', name='uq_daily_report_owner_date')
    )
    op.create_index(op.f('ix_daily_reports_date'), 'daily_reports', ['date'], unique=False)
    op.create_index(op.f('ix_daily_reports_owner'), 'daily_reports', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_reports_owner'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_date'), table_name='daily_reports')
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
